#!/bin/bash

LOG_FILE="${TRIM_PKGVAR}/info.log"
PID_FILE="${TRIM_PKGVAR}/app.pid"

# write the command to start your program here
CMD=""

log_msg() {
  echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >>${LOG_FILE}
}

start_process() {
  if status; then
    return 0
  fi

  log_msg "Starting process ..."
	modprobe -r b43 b43legacy b44 bcma brcm80211 brcmsmac ssb >>${LOG_FILE} 2>&1
  insmod "${TRIM_APPDEST}/server/src/wl.ko" >>${LOG_FILE} 2>&1
  return 0
}

stop_process() {
  log_msg "Stopping process ..."
  rmmod "${TRIM_APPDEST}/server/src/wl.ko" >>${LOG_FILE} 2>&1
	modprobe b43 b43legacy b44 bcma brcm80211 brcmsmac ssb >>${LOG_FILE} 2>&1
  return 0
}

status() {
  lsmod | grep -q '^wl\b' 2>/dev/null
  return $?
}	

case $1 in
  start)
    # run start command. exit 0 if success, exit 1 if failed
    start_process
    ;;
  stop)
    # run stop command. exit 0 if success, exit 1 if failed
    stop_process
    ;;
  status)
    # check application status command. exit 0 if running, exit 3 if not running
    if status; then
      exit 0
    else
      exit 3
    fi
    ;;
  *)
    exit 1
    ;;
esac
