#!/bin/bash

### This script is called after the user installs the application.

KVER="$(uname -r)"
SVER="$(echo "${KVER}" | cut -d'.' -f1,2)"

# Prepare build environment
if [ ! -f "${TRIM_APPDEST}/server/src/${SVER}/Makefile" ]; then
  echo "Source code for kernel version ${SVER} not found."
  exit 1
fi

PRE_INSTALLED=$(mktemp)
dpkg --get-selections | grep -E 'install$' | awk '{print $1}' > "${PRE_INSTALLED}"

# Install build dependencies
apt update
apt install -y --no-install-recommends build-essential
[ $? -ne 0 ] && echo "Install build-essential failed." && exit 1

POST_INSTALLED=$(mktemp)
dpkg --get-selections | grep -E 'install$' | awk '{print $1}' > "${POST_INSTALLED}"

# Build the module
make -C /lib/modules/${KVER}/build M="${TRIM_APPDEST}/server/src/${SVER}" CONFIG_NTFS3_FS=m CONFIG_NTFS3_LZX_XPRESS=y modules
RET=$?
strip -g "${TRIM_APPDEST}/server/src/${SVER}/ntfs3.ko" 2>/dev/null || true

# Remove build dependencies
TO_REMOVE=$(comm -13 "${PRE_INSTALLED}" "${POST_INSTALLED}" | xargs)
rm -f "${PRE_INSTALLED}" "${POST_INSTALLED}"
if [ -n "${TO_REMOVE}" ]; then
  apt purge -y ${TO_REMOVE}
  apt autoremove -y
fi

if [ $RET -ne 0 ] || [ ! -f "${TRIM_APPDEST}/server/src/${SVER}/ntfs3.ko" ]; then
  echo "Build ntfs3 module failed."
  exit 1
fi

# Install the module
mkdir -p /usr/lib/modules/${KVER}/updates/fs
rm -f /usr/lib/modules/${KVER}/updates/fs/ntfs3.ko 2>/dev/null || true
cp -vpf "${TRIM_APPDEST}/server/src/${SVER}/ntfs3.ko" /usr/lib/modules/${KVER}/updates/fs/ntfs3.ko

depmod -a || true
echo ntfs3 >/etc/modules-load.d/ntfs3.conf

# Restart systemd-modules-load.service to load the module
systemctl restart systemd-modules-load.service

# Replace the mount.ntfs symlink to point to mount.ntfs3
rm -f /usr/sbin/mount.ntfs && echo -e '#!/bin/sh\nmount -t ntfs3 "$@"' >/usr/sbin/mount.ntfs && chmod a+x /usr/sbin/mount.ntfs

exit $?
